### ISSUE TITLE
New version of uipath CLI

### ISSUE THREAD

**Issue by MaddRaphael** [Mikael-RnD/setup-uipath#165]
Hello,

Since October 11th, a new version of uipath CLI is available, “24.10.9050.17872”.

https://docs.uipath.com/fr/automation-ops/automation-cloud/latest/USER-GUIDE/release-notes-uipath-cli

Have a nice day.

**Comment by mikael-andersson91** [comment]
Hi @MaddRaphael, thanks for bringing this to my attention! 

As of this commit (https://github.com/Mikael-RnD/setup-uipath/commit/a1a20ef72bbb00d54dcad88834efccc110566e97), the action uses version 24.10.9050.17872 as the default version of the UiPath CLI.

I also checked the feed now, and it looks like there were multiple new versions released in December. I will update the action to use the latest version by default.

I should however note, that if the action is not kept up to date or you wish to use an older version of the CLI, you can always use the **version** input on the action to pin which version of the CLI you want to use in your workflow. See the example below for pinning to the latest version at the time of writing, 24.12.9111.31003:

```yml
      # Set up the UiPath CLI (uipcli) and add it to PATH on your runner
      - name: Setup UiPath (uipcli) command line tool
        uses: Mikael-RnD/setup-uipath@v1
        with:
          version: 24.12.9111.31003
```
